version: "3"

vars:
    CPP_SRCS: {sh: find src -type f -iregex ".*\.cpp"}
    # EX1: mycontainerimage
    # EX2: {sh: git-rev parse HEAD}
    # EX3: "{{.CONTAINER_IMAGE_NAME}}:{{.CONTAINER_IMAGE}}"
    ARGS: -ffreestanding
          -m32
          -c
          -g
          -mgeneral-regs-only
          -Wreturn-local-addr
          -mno-red-zone


tasks:
  default:
    desc: Compile Cpp
    cmds:
      - g++ {{.CPP_SRCS}} -I ./include {{.ARGS}}
