#! /usr/bin/python3
import os
import glob

def main():
	# === PARAMETERS === #
	args = "-ffreestanding -m32 -g -c -mgeneral-regs-only -Wall"
	gcc = "/usr/local/i386elfgcc/bin/i386-elf-g++"
	include = "../include"
	cppFiles = formatList(glob.glob("./src/*.cpp"))

	# === PROGRAM === #
	
	
	# change working directory
	os.chdir("./build")

	# compile all cpp files into object files
	os.system(f"{gcc} {args} {cppFiles} -I {include}")


	print(cppFiles)


def formatList(list):
	formattedFiles = str()
	for file in list:
		# temp = str(file).removeprefix("./src/")
		temp = str(file)

		formattedFiles = f'{formattedFiles}../{temp} '
	return formattedFiles
	# glob.glob("./src/*.cpp")

if __name__ == "__main__":
	main()